--insert into member(member_id,username, city, street, zipcode) values(1L, '김진규', '서울', '강남', '11111');
--insert into item(dtype, item_id, name, price, stock_quantity) values('Book', 1L, '정석', 8000, 1000);
