spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#        show_sql: true   -> 콘솔에 말고 log 로 남기자
        format_sql: true

logging.level:
  org.hibernate.SQL: debug  # 로그로 sql 남기기
#  org.hibernate.type: trace # 파라미터 바인딩 쿼리 보기